# Generated by Django 5.2.6 on 2025-09-28 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_profesional', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_especifica', 'Prefiero no especificar')], max_length=20, verbose_name='Género')),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión libre')], max_length=20, verbose_name='Estado Civil')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('documento_id', models.CharField(max_length=50, unique=True, verbose_name='Documento de Identidad')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconocido', 'Desconocido')], max_length=11, verbose_name='Tipo de Sangre')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura', models.IntegerField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('medicamentos_actuales', models.TextField(blank=True, verbose_name='Medicamentos Actuales')),
                ('enfermedades_cronicas', models.TextField(blank=True, verbose_name='Enfermedades Crónicas')),
                ('antecedentes_familiares', models.TextField(blank=True, verbose_name='Antecedentes Familiares')),
                ('fuma', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ocasional', 'Ocasional')], max_length=10)),
                ('alcohol', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ocasional', 'Ocasional')], max_length=10)),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono Principal')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alternativo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, verbose_name='Email Alternativo')),
                ('emergencia_nombre', models.CharField(max_length=100, verbose_name='Contacto de Emergencia')),
                ('emergencia_parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('emergencia_telefono', models.CharField(max_length=20, verbose_name='Teléfono de Emergencia')),
                ('emergencia_telefono2', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Emergencia 2')),
                ('seguro_medico', models.CharField(blank=True, max_length=100, verbose_name='Seguro Médico')),
                ('numero_poliza', models.CharField(blank=True, max_length=50, verbose_name='Número de Póliza')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirugias_previas', models.TextField(blank=True, verbose_name='Cirugías Previas')),
                ('hospitalizaciones', models.TextField(blank=True, verbose_name='Hospitalizaciones')),
                ('traumatismos', models.TextField(blank=True, verbose_name='Traumatismos')),
                ('menarquia', models.CharField(blank=True, max_length=50, verbose_name='Menarquía')),
                ('ciclo_menstrual', models.CharField(blank=True, max_length=100, verbose_name='Ciclo Menstrual')),
                ('embarazos', models.IntegerField(blank=True, null=True, verbose_name='Embarazos')),
                ('partos', models.IntegerField(blank=True, null=True, verbose_name='Partos')),
                ('cesareas', models.IntegerField(blank=True, null=True, verbose_name='Cesáreas')),
                ('abortos', models.IntegerField(blank=True, null=True, verbose_name='Abortos')),
                ('notas_importantes', models.TextField(blank=True, verbose_name='Notas Importantes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi_app.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Expediente Médico',
                'verbose_name_plural': 'Expedientes Médicos',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tipo_consulta', models.CharField(choices=[('general', 'Consulta General'), ('seguimiento', 'Seguimiento'), ('urgencia', 'Urgencia'), ('control', 'Control'), ('primera_vez', 'Primera Vez')], max_length=20, verbose_name='Tipo de Consulta')),
                ('motivo', models.TextField(verbose_name='Motivo de la Consulta')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=20, verbose_name='Estado')),
                ('sintomas', models.TextField(blank=True, verbose_name='Síntomas')),
                ('exploracion_fisica', models.TextField(blank=True, verbose_name='Exploración Física')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima Cita')),
                ('presion_arterial', models.CharField(blank=True, max_length=20, verbose_name='Presión Arterial')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Cardíaca')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura')),
                ('peso_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso en Consulta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
