# Generated by Django 5.2.6 on 2025-09-28 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración del Tratamiento')),
                ('indicaciones', models.TextField(blank=True, verbose_name='Indicaciones Especiales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.consultation', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
