# Generated by Django 5.2.6 on 2025-11-11 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='documento_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fuma',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ocupacion',
        ),
        migrations.AddField(
            model_name='patient',
            name='calle',
            field=models.CharField(default='Sin especificar', max_length=200, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ciudad',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='patient',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='colonia',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='estado',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero',
            field=models.CharField(default='S/N', max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencia_nombre',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Contacto de Emergencia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencia_parentesco',
            field=models.CharField(default='Sin especificar', max_length=50, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencia_telefono',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión libre')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telefono_principal',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Teléfono Principal'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconocido', 'Desconocido')], max_length=15, verbose_name='Tipo de Sangre'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('recepcionista', 'Recepcionista')], default='doctor', max_length=20)),
                ('cedula_profesional', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'user_profiles',
            },
        ),
    ]
