# Generated by Django 5.2.6 on 2025-11-12 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_remove_patient_alcohol_remove_patient_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('tipo_comprobante', models.CharField(choices=[('factura', 'Factura (CFDI)'), ('recibo', 'Recibo Simple'), ('nota', 'Nota de Venta')], default='recibo', max_length=20, verbose_name='Tipo de Comprobante')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('cliente_rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('cliente_direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='mi_app.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('paypal', 'PayPal'), ('otro', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Folio')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='mi_app.consultation', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='mi_app.payment', verbose_name='Pago'),
        ),
    ]
