# Generated by Django 5.2.6 on 2025-11-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_invoice_conceptofactura_payment_invoice_payment'),
    ]

    operations = [
    ]
